name: Devops real project 2

on:
  push:
    branches: ["main"]

jobs:
  devops-real-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: pip install -r requirements.txt

    - name: Formatting test
      run: black .
    
    - name: Linting test
      run: black .
    
    - name: Static analysis 
      run: bandit -r . --skip B101,B102,B104

    - name: Unit test
      run: pytest test_app.py

    - name: Dockerhub login               #Creds added in git repo
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image 
      run: docker build -t shepherd777/devops-real-2:latest .

    - name: Push image to dockerhub
      run: docker push shepherd777/devops-real-2:latest

